"""
Revision ID: 3aecad6b286a
Revises:
Create Date: 2025-12-21 16:02:19.874634
"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = "3aecad6b286a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets_tickets",
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column(
            "task_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            default=uuid.uuid4,
            nullable=True,
        ),
        sa.Column(
            "person_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            default=uuid.uuid4,
            nullable=False,
        ),
        sa.Column(
            "assignee_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            default=uuid.uuid4,
            nullable=True,
        ),
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            default=uuid.uuid4,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tickets_tickets_assignee_id"),
        "tickets_tickets",
        ["assignee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tickets_tickets_person_id"),
        "tickets_tickets",
        ["person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tickets_tickets_task_id"),
        "tickets_tickets",
        ["task_id"],
        unique=False,
    )
    op.add_column(
        "preview_file",
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("preview_file", "data")
    op.drop_index(
        op.f("ix_tickets_tickets_task_id"), table_name="tickets_tickets"
    )
    op.drop_index(
        op.f("ix_tickets_tickets_person_id"), table_name="tickets_tickets"
    )
    op.drop_index(
        op.f("ix_tickets_tickets_assignee_id"), table_name="tickets_tickets"
    )
    op.drop_table("tickets_tickets")
    # ### end Alembic commands ###
