"""
Revision ID: a7b8c9d0e1f2
Revises: 3aecad6b286a
Create Date: 2025-01-27 12:00:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a7b8c9d0e1f2"
down_revision = "3aecad6b286a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ticket_status_enum = sa.Enum("open", "on hold", "closed", name="ticket_status")
    ticket_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "plugin_tickets_tickets",
        sa.Column(
            "status",
            ticket_status_enum,
            nullable=False,
            server_default="open",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plugin_tickets_tickets", "status")
    ticket_status_enum = sa.Enum(name="ticket_status")
    ticket_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

