"""

Revision ID: d170217a4f39
Revises: a7b8c9d0e1f2
Create Date: 2026-01-08 22:36:20.674077

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd170217a4f39'
down_revision = 'a7b8c9d0e1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin_tickets_tickets', 'person_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_plugin_tickets_tickets_assignee_id', table_name='plugin_tickets_tickets')
    op.drop_index('ix_plugin_tickets_tickets_person_id', table_name='plugin_tickets_tickets')
    op.drop_index('ix_plugin_tickets_tickets_task_id', table_name='plugin_tickets_tickets')
    op.create_index(op.f('ix_plugin_tickets_tickets_assignee_id'), 'plugin_tickets_tickets', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_plugin_tickets_tickets_person_id'), 'plugin_tickets_tickets', ['person_id'], unique=False)
    op.create_index(op.f('ix_plugin_tickets_tickets_task_id'), 'plugin_tickets_tickets', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_tickets_tickets_task_id'), table_name='plugin_tickets_tickets')
    op.drop_index(op.f('ix_plugin_tickets_tickets_person_id'), table_name='plugin_tickets_tickets')
    op.drop_index(op.f('ix_plugin_tickets_tickets_assignee_id'), table_name='plugin_tickets_tickets')
    op.create_index('ix_plugin_tickets_tickets_task_id', 'plugin_tickets_tickets', ['task_id'], unique=False)
    op.create_index('ix_plugin_tickets_tickets_person_id', 'plugin_tickets_tickets', ['person_id'], unique=False)
    op.create_index('ix_plugin_tickets_tickets_assignee_id', 'plugin_tickets_tickets', ['assignee_id'], unique=False)
    op.alter_column('plugin_tickets_tickets', 'person_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
