"""

Revision ID: dd94e3d1cb02
Revises: d170217a4f39
Create Date: 2026-01-08 23:17:03.858797

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd94e3d1cb02'
down_revision = 'd170217a4f39'
branch_labels = None
depends_on = None



TICKET_STATUSES = [
    ("open", "Open"),
    ("on hold", "On Hold"),
    ("closed", "Closed"),
]



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin_tickets_tickets', 'status',
               existing_type=postgresql.ENUM('open', 'on hold', 'closed', name='ticket_status'),
               type_=sqlalchemy_utils.types.choice.ChoiceType(TICKET_STATUSES),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::ticket_status"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin_tickets_tickets', 'status',
               existing_type=sqlalchemy_utils.types.choice.ChoiceType(TICKET_STATUSES),
               type_=postgresql.ENUM('open', 'on hold', 'closed', name='ticket_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::ticket_status"))
    # ### end Alembic commands ###
