"""

Revision ID: ec26770a2414
Revises: dd94e3d1cb02
Create Date: 2026-01-11 23:14:29.159408

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = 'ec26770a2414'
down_revision = 'dd94e3d1cb02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin_tickets_tickets', sa.Column('project_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True))
    op.create_index(op.f('ix_plugin_tickets_tickets_project_id'), 'plugin_tickets_tickets', ['project_id'], unique=False)
    op.create_foreign_key(None, 'plugin_tickets_tickets', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plugin_tickets_tickets', type_='foreignkey')
    op.drop_index(op.f('ix_plugin_tickets_tickets_project_id'), table_name='plugin_tickets_tickets')
    op.drop_column('plugin_tickets_tickets', 'project_id')
    # ### end Alembic commands ###
